steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/convoc-app:$COMMIT_SHA'
      - '.'

  # 2️⃣ Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/convoc-app:$COMMIT_SHA'

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - 'convoc-app'                 # Cloud Run service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/convoc-app:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'               # region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/convoc-app:$COMMIT_SHA'
